### ISSUE TITLE
Discord link expired

### ISSUE THREAD

**Issue by kumarsyadav2** [Arsenic-ATG/Arsenic-ATG#10]
Hey there! whenever i am on the Discord link provided on your Github profile, it is saying "Uh oh! We can't view details for this user". I think your link got expired so kindly look into it and add your Discord profile link again.
Thanks!

**Comment by Arsenic-ATG** [comment]
thanks for opening this issue. 

check this link, does this work ?

https://discordapp.com/users/711927506445533205/

**Comment by kumarsyadav2** [comment]
No, again it's not working!

This link too gives the same error message as before

Please try to fix it again!

**Comment by Arsenic-ATG** [comment]
This looks like a discord bug to me, because I asked some other people to check the link, and it seem to work for them. 

Which version of discord are you using ?

**Comment by kumarsyadav2** [comment]
My discord version is "Version 88.14 - Stable" hopefully it is the latest version.

Idk why it's not working for me!!!

**Comment by Arsenic-ATG** [comment]
My discord username is `Arsenic#9256`, can you try the search feature of the app itself to see if I pop up in there or not ?

**Comment by kumarsyadav2** [comment]
Sure! Let's connect there

**Comment by Arsenic-ATG** [comment]
nice, could you also provide your discord username, so that I can confirm that I was contacted by right person.

**Comment by kumarsyadav2** [comment]
Yeah sure!! I have already sent you request on discord.
My discord I'd - saurabh#0459 {saurabh#(zero,four,five,nine)}

Hope you got that!!!
