### ISSUE TITLE
Add new twitter badge for profile

### ISSUE THREAD

**Issue by Arsenic-ATG** [Arsenic-ATG/Arsenic-ATG#11]
twitter profile link : https://twitter.com/AR3N1C

**Comment by Arsenic-ATG** [comment]
badge can be created on https://shields.io

examples can be seen at the end of the README.md file 

Screen shots : 

<img width="1205" alt="Screenshot 2022-09-28 at 4 59 49 PM" src="https://user-images.githubusercontent.com/54987647/192767952-bbbaddca-af98-44c1-9c49-7378b7629073.png">

**Comment by shishirkj** [comment]
please assign this to me

**Comment by Arsenic-ATG** [comment]
> please assign this to me

Ok

**Comment by Arsenic-ATG** [comment]
marked completed after merging #32
