### ISSUE TITLE
use references instead of hyperlinks

### ISSUE THREAD

**Issue by Arsenic-ATG** [Arsenic-ATG/Arsenic-ATG#15]
it's much better to use reference instead of hard-coding the hyperlinks in the profile readme, though it would not make any difference in the actual looks of the readme, but would make the readme more readable and manageable for someone who is willing to read/contribute to the source code

**Comment by Arsenic-ATG** [comment]
This is how to make references in GitHub flavoured markdowns (GLF)

```md
[alt text](link_reference)

[link_reference]: actual link address
```

**Comment by bhavy2202** [comment]
Is this still open?

**Comment by Arsenic-ATG** [comment]
@bhavy2202 indeed

**Comment by Arsenic-ATG** [comment]
let me know if you are interested, I will assign you this to avoid any future misunderstanding.

**Comment by bhavy2202** [comment]
yes, please assign me.

**Comment by shishirkj** [comment]
please assign this to me and please help me as to where to add the refernce link 🙂 thank you

**Comment by Arsenic-ATG** [comment]
> please assign this to me and please help me as to where to add the refernce link 🙂 thank you

All the references should be present at the end of the file. 
If you have any better idea then please feel free to share here.

**Comment by shishirkj** [comment]
Can you please tell me as to where i should make differences

**Comment by Arsenic-ATG** [comment]
> Can you please tell me as to where i should make differences

@shishirkj , sorry for late reply ( I was busy with my university exams )

It appears that Github doesn't support direct references from the current page but instead only uses it for footnotes and direct links.
Thanks for pointing this out, I would be closing this issue now.
