### ISSUE TITLE
Add "contact me" section

### ISSUE THREAD

**Issue by Arsenic-ATG** [Arsenic-ATG/Arsenic-ATG#2]
Currently there is no official way to contact me from GitHub.

TODO: 
update the readme to contain links to some of my public profiles for other to contact me.

**Comment by BeegCat** [comment]
I admire your immense knowledge in multiple programming langauges (he's a student yet knows a lot by now). I look forward for contributing to your projects :D

**Comment by Arsenic-ATG** [comment]
Greetings @BeegCat and thanks for appreciation. 

I don't think there is much you can do to update the " contact me " section of my profile readme but still if you want to contribute then you can help in creation of icons for the that section. 

I was thinking of using [shilds.io](https://shields.io) for creating icons for the section. 

I am also thinking to update [**Languages and Tools**](https://github.com/Arsenic-ATG/Arsenic-ATG#languages-and-tools-) section with the badges from shields instead of using images for the same.

If this interests you then try creating some and share some samples here for review.
