### ISSUE TITLE
make "skills" section collapsable 

### ISSUE THREAD

**Issue by Arsenic-ATG** [Arsenic-ATG/Arsenic-ATG#20]
The skills section is quite large in the readme and takes quite a bit of space on main page requiring the visitor to scroll more to actually reach to the contribution chats and the repositories. 

According to me the skills section should be collapsable ( like profile readme stats section )

**Comment by bhavy2202** [comment]
Please assign this to me

**Comment by Arsenic-ATG** [comment]
@bhavy2202 , are you still working ( or planning to work ) on this issue ? 

If you are busy with something else, I think maybe I can take over the issue from here and work on it.
In case you are still wiling to work on the issue, then do let me know, I would wait.
