### ISSUE TITLE
Activity graph not working as horeku servers are down

### ISSUE THREAD

**Issue by Arsenic-ATG** [Arsenic-ATG/Arsenic-ATG#22]
see https://github.com/Ashutosh00710/github-readme-activity-graph/issues/55 for more information

I would be temporarily removing the graph from the readme till the time either the server get's refreshed or I create a custom solution of the same.

**Comment by Ashutosh00710** [comment]
@Arsenic-ATG Use this URL to render your graph. You can close this issue.
```md
<img height="295em" src="https://github-readme-activity-graph.cyclic.app/graph?username=arsenic-atg&hide_border=true&theme=nord" />
```
<img height="295em" src="https://github-readme-activity-graph.cyclic.app/graph?username=arsenic-atg&hide_border=true&theme=nord" />

**Comment by Arsenic-ATG** [comment]
> @Arsenic-ATG Use this URL to render your graph. You can close this issue.
> 
> ```lisp
> <img height="295em" src="https://github-readme-activity-graph.cyclic.app/graph?username=arsenic-atg&hide_border=true&theme=nord" />
> ```
> 
> <img alt="" height="295em" src="https://camo.githubusercontent.com/0c31db25d033e1af45b540308cdc46c026a6f9646e44189e8614ee45f8eebdd5/68747470733a2f2f6769746875622d726561646d652d61637469766974792d67726170682e6379636c69632e6170702f67726170683f757365726e616d653d617273656e69632d61746726686964655f626f726465723d74727565267468656d653d6e6f7264">

Thank you 🙂
