### ISSUE TITLE
add php and laravel to skills section

### ISSUE THREAD

**Issue by Arsenic-ATG** [Arsenic-ATG/Arsenic-ATG#28]
I am currently in process of learning laravel framework and PHP in general thanks to my new internship, I suppose it should be a good idea to add them the skills section of the profile `README.md` with appropriate badges

**Comment by Arsenic-ATG** [comment]
`![laravel](https://img.shields.io/badge/Laravel-%23434C5E?style=for-the-badge&logo=Laravel&labelColor=%23FF2D20&logoColor=white)`

![laravel](https://img.shields.io/badge/Laravel-%23434C5E?style=for-the-badge&logo=Laravel&labelColor=%23FF2D20&logoColor=white)

---

`![php](https://img.shields.io/badge/php-%23434C5E?style=for-the-badge&logo=php&labelColor=%23777BB4&logoColor=white)`

![php](https://img.shields.io/badge/php-%23434C5E?style=for-the-badge&logo=php&labelColor=%23777BB4&logoColor=white)

**Comment by shishirkj** [comment]
please assign this to me

**Comment by Arsenic-ATG** [comment]
marking as complete afters succefull merging of #37
