### ISSUE TITLE
Add attributions of the widgets I use on readme

### ISSUE THREAD

**Issue by Arsenic-ATG** [Arsenic-ATG/Arsenic-ATG#29]
Some of the things I use on my readme to make them look more appealing are creations projects of other great developers which should be attributed in someway or the other.

Some of the possible ideas include 
- Creating THANK_YOU.md with list of all the people thanks to which the readme looks like what it is now.
- adding link to the original projects of widgets I use on my readme ( like readme stats, tropies, graph etc ) 

---

If you have any idea then feel free to comment on this issue thread

**Comment by shishirkj** [comment]
please assign this to me

**Comment by Arsenic-ATG** [comment]
@shishirkj thanks for showing interest in this one

Here are the repository links of projects used in the README.md

- readme stats (https://github.com/anuraghazra/github-readme-stats )
- trophies ( https://github.com/ryo-ma/github-profile-trophy )
- activity graph (https://github.com/Ashutosh00710/github-readme-activity-graph )

---

If you have any doubt or need any further clarification about the profile readme then feel free to ask here. 🙂

**Comment by Arsenic-ATG** [comment]
closing after successful merge of #34 and #38
