### ISSUE TITLE
 Widgets not working in skills section

### ISSUE THREAD

**Issue by shishirkj** [Arsenic-ATG/Arsenic-ATG#31]
Some of the widgets are not link to the respective sites in skills section

**Comment by shishirkj** [comment]
please assign this to me

**Comment by Arsenic-ATG** [comment]
thanks for showing interest in this and opening an issue 
but the project already have an open issue ( #14 )  which is basically the same. Thus marking this as a duplicate ( I have assigned you that one though ) 

--- 

In case you think this is different from #14 then feel free to leave a comment here and we can open the issue again.
